/**
 * lib/policy/audit/types.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * AYZEN Policy & Authorization Mega Engine — Phase 17 (Authorization Audit).
 *
 * Pure types. No DB, no Express — same discipline every other lib/policy/*
 * types.ts file already follows (see e.g. ../assurance/types.ts's header).
 *
 * The roadmap's own Phase 17 section, verbatim field list:
 *   decisionId, requestId, subject reference, product, resource, action,
 *   decision, policyId, policyVersion, risk, assurance, timestamp, latency,
 *   reasonCode — plus "Avoid unnecessary sensitive data" and "Integrate
 *   with existing AYZEN activity/security logging".
 *
 * `AuthorizationAuditEntry` below is exactly that field list, typed. It is
 * built ONLY by `toAuditEntry()` (./to-audit-entry.ts) from an already-
 * finalized `AuthorizationDecision` + the `AuthorizationRequest` that
 * produced it — never hand-constructed at a call site — so every writer
 * (a real `DrizzleAuthorizationAuditWriter`, a test's in-memory fake, or a
 * future non-Postgres sink) is guaranteed to receive the exact same shape,
 * built by the exact same rules about what is and isn't safe to persist.
 *
 * ── Why this is a NEW seam, not a change to decision-observer.ts ─────────
 * `decision-observer.ts` (Phase 1C) already said this explicitly in its own
 * header: "This is intentionally NOT Phase 17 ... Phase 17 can build real,
 * queryable audit storage on top of this same `onDecision` seam later
 * without touching the engine again." This module is that promise kept —
 * `createAuthorizationAuditObserver()` (./audit-observer.ts) is a SECOND,
 * independent `PolicyDecisionObserver` built the same way
 * `createLoggingObserver()` was, not a replacement for it. An app wiring
 * both together (structured logs AND a durable audit row for the same
 * decision) is expected and fine — `PolicyEngine` only ever accepts one
 * `onDecision` callback, so a caller that wants both composes them (call
 * one, then the other) rather than this module reaching in to do so itself.
 *
 * ── "Subject reference", not "subject" ────────────────────────────────────
 * The roadmap says "subject reference", not "subject" — deliberately not
 * the full `Subject` object (which can carry `scopes`, an API key's
 * `keyType`, etc.). Only the fields needed to identify WHO and answer
 * basic audit queries ("show me every decision for user 42",
 * "show me every apikey-authenticated decision") are kept — see
 * `AuthorizationAuditEntry`'s own subject* fields below and
 * `to-audit-entry.ts`'s header for the full "what's deliberately excluded"
 * rationale.
 */

import type { AuthorizationDecision, DecisionEffect, SubjectAuthType } from "../types";
import type { DecisionReasonCode } from "../decision-reasons";

/**
 * One durable row: the roadmap's Phase 17 field list, made concrete.
 * Every field here is either copied verbatim from the triggering
 * `AuthorizationDecision`/`AuthorizationRequest`, or derived by a pure,
 * documented rule (`product`, see to-audit-entry.ts's `deriveProduct()`) —
 * nothing here is guessed or independently computed.
 */
export interface AuthorizationAuditEntry {
  /** Identifies THIS audit row/event, distinct from `requestId` (the
   *  correlation id of the authorization REQUEST that produced it — one
   *  request always produces exactly one decision and therefore exactly
   *  one audit entry today, but the two ids are kept conceptually
   *  separate, same posture the roadmap's own field list draws by listing
   *  both, and same reasoning `../policy-context.ts`'s own
   *  `requestId`-vs-nothing-else split already established). Generated by
   *  `toAuditEntry()` itself via `node:crypto`'s `randomUUID()` — the
   *  exact same generation strategy `createPolicyContext()` already uses
   *  for `requestId` — so every writer (real or fake) receives a fully
   *  self-contained entry and never has to invent an id of its own. */
  decisionId: string;
  /** Copied from `decision.requestId` — see ../types.ts's own doc comment
   *  on `PolicyContext.requestId` for the correlation-ID contract this
   *  mirrors. */
  requestId: string;

  // ── Subject reference (WHO) — see file header's "not `Subject`" note ──
  /** `undefined` when the request was unauthenticated
   *  (`request.subject === null`, e.g. an UNAUTHENTICATED decision) — a
   *  row is still written for that case (a denied anonymous attempt is
   *  exactly the kind of thing an audit trail exists to capture), just
   *  with no subject identity to attach. */
  subjectUserId?: number;
  subjectRole?: string;
  subjectAuthType?: SubjectAuthType;
  subjectOrganizationId?: number | null;

  /** The roadmap's own "product" field — the first dot-segment of
   *  `request.action` when it follows the `product.resource.action`
   *  grammar (../rbac/permission-matcher.ts), e.g. `"sylo"` from
   *  `"sylo.vault.read"`. `undefined` for a Phase 01-style opaque action
   *  that doesn't follow that grammar — see to-audit-entry.ts's
   *  `deriveProduct()` for the exact rule; never guessed from
   *  `resource.type` instead (see that function's own header for why). */
  product?: string;
  /** `request.resource.type` verbatim, e.g. `"sylo.vault_item"`. */
  resourceType?: string;
  /** `request.resource.id`, stringified (a `ResourceRef.id` may be a
   *  number or a string — normalized here to one column type). */
  resourceId?: string;
  /** `request.action` verbatim (the full string — not just the derived
   *  `product` segment). */
  action?: string;

  /** The decision's own effect — ALLOW/DENY/STEP_UP/APPROVAL_REQUIRED.
   *  Named `decision` (not `effect`) to match the roadmap's own field
   *  list wording exactly. */
  decision: DecisionEffect;
  reasonCode: DecisionReasonCode;

  /** Copied verbatim from `decision.policyId`/`decision.policyVersion` —
   *  `undefined` for a decision not produced by a registry-backed rule,
   *  same posture every other Phase 02-16 consumer of these two fields
   *  already takes (see ../types.ts's own doc comments on them). */
  policyId?: string;
  policyVersion?: number;

  /** Copied from `request.subject.riskLevel` (Phase 05/10) — this module
   *  never computes risk itself, same "Risk Engine calculates, Policy
   *  Engine decides" boundary ../risk/risk-rule.ts's own header draws;
   *  this is one step further removed still — an audit ENTRY, not even a
   *  decision — so it only ever surfaces whatever was already on the
   *  request. `undefined` when absent. */
  risk?: "low" | "medium" | "high";
  /** The subject's own satisfied assurance methods for this session
   *  (`request.subject.assuranceMethods`, e.g. `["password", "totp"]`) —
   *  what the subject HAD. Kept distinct from `requiredAssurance` below
   *  (what the DECISION demanded), same split ../explain/types.ts's
   *  `PolicyExplanationDetail` already draws between `assuranceLevel` and
   *  `requiredAssurance`. `undefined` when the subject had none on file
   *  (never written as an empty array — see to-audit-entry.ts). */
  assuranceMethods?: string[];
  /** Copied from `decision.requiredAssurance` — set only for a STEP_UP
   *  gated on a named minimum assurance level (today: only
   *  ../assurance/assurance-rule.ts). */
  requiredAssurance?: string;

  /** Copied from `decision.evaluatedAt` — WHEN the PDP produced this
   *  decision (distinct from `createdAt`, which a writer stamps at
   *  persistence time — normally near-identical, kept separate on
   *  principle the same way every other audit table in this codebase
   *  already does, e.g. `vault_backup_audit_log`'s own `created_at`
   *  versus the event it describes). */
  timestamp: Date;
  /** Copied from `decision.latencyMs` (Phase 17's own addition to
   *  `AuthorizationDecision` — see ../policy-engine.ts's `stampLatency()`
   *  and ../types.ts's doc comment on that field). `undefined` only for a
   *  decision that was never run through `PolicyEngine.evaluate()`/
   *  `evaluateWithTrace()` at all. */
  latencyMs?: number;
}

/**
 * The write half of this seam. Deliberately as small as
 * `PolicyRegistryProvider`/`RelationshipProvider`/every other Phase 02-16
 * provider interface this engine already defines — one real
 * (`DrizzleAuthorizationAuditWriter`, ./drizzle-audit-writer.ts) and one
 * fake (a test's in-memory array) implementation, same "one shared
 * interface" shape every prior phase's own provider header documents.
 *
 * MUST fail closed in the sense that mattered from Phase 01 onward: a
 * writer that throws must NEVER be allowed to turn a logging failure into
 * an authorization failure. That guarantee is NOT this interface's job to
 * enforce (an interface cannot catch anything) — it is
 * `createAuthorizationAuditObserver()`'s (./audit-observer.ts), which
 * always wraps every `write()` call the exact same defensive way
 * `createLoggingObserver()` already wraps every logger call.
 */
export interface AuthorizationAuditWriter {
  write(entry: AuthorizationAuditEntry): Promise<void>;
}
