/**
 * services/deposit-watcher.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Real-time deposit detection for the AYZEN vault wallet across five EVM
 * chains: Ethereum (ETH), BNB Chain (BNB), Polygon (POL), Plasma (XPL), and
 * Arbitrum (ETH gas + the separate ARB token). Every chain's `tokens` list
 * (USDT everywhere, USDC on ETH/BSC/MATIC/ARB, plus ARB on Arbitrum) is
 * watched for ERC-20 deposits alongside the native coin — this list is
 * entirely driven by lib/tokens.ts, so adding a new token/chain row there
 * is all that's needed for the watcher to pick it up. The custodial wallet
 * address generated by
 * POST /wallets/builtin/create is the SAME address on every one of these
 * chains (one EVM keypair), so a user only ever needs to be shown one
 * deposit address + a network picker.
 *
 * How it works (poll-based, since free public RPCs don't offer reliable
 * WebSocket subscriptions):
 *   1. Every POLL_INTERVAL_MS, for each chain: read the latest block number
 *      and scan every block since the last cursor for (a) native-coin
 *      transfers whose `to` is a tracked wallet address, and (b) ERC-20
 *      Transfer logs (via eth_getLogs — cheap, no full block fetch needed)
 *      for the chain's configured stablecoin contract(s) whose `to` topic
 *      is a tracked address.
 *   2. The instant a matching tx/log is seen, it's written to
 *      chain_deposits as `status: 'pending'` and broadcast over SSE
 *      (`deposit_detected`) — this is the "real-time" part, usually a few
 *      seconds after the tx lands.
 *   3. On each subsequent poll, pending deposits have their `confirmations`
 *      recomputed from the current chain height. Once a deposit crosses the
 *      chain's required confirmation count, its amount is credited to the
 *      user (native → that wallet row's `balance`; stablecoin → the
 *      `builtin_wallet_tokens` ledger) and marked `credited` + `confirmed`,
 *      broadcasting `deposit_confirmed`.
 *
 * This mirrors the existing withdrawal path (routes/wallets.ts
 * handleWithdraw): withdrawals sign + broadcast outbound, this service
 * watches inbound — together they're the vault wallet's full deposit/
 * withdrawal loop.
 */
import { ethers } from "ethers";
import { db, pool, walletsTable, chainDepositsTable, builtinWalletTokensTable } from "@workspace/db";
import { eq, sql as dsql } from "drizzle-orm";
import { broadcastEvent } from "../routes/events";
import { logBus } from "../lib/log-bus";
import { logger } from "../lib/logger";
import { tokensForChain } from "../lib/tokens";
import { postDepositToFinance } from "../lib/finance-wallet-bridge";

export interface ChainConfig {
  chain: string;         // matches wallets.chain / networks.chain
  rpcUrl: string;
  chainId: number;
  nativeSymbol: string;
  confirmationsRequired: number;
  blockRangePerPoll: number; // safety cap so one poll never scans an unbounded range
  /** ERC-20 stablecoins to watch for on this chain. */
  tokens: { symbol: string; contract: string; decimals: number }[];
}

// ERC-20s watched per chain, sourced from lib/tokens.ts so this list can
// never drift out of sync with the withdrawal-side resolver.
function erc20sFor(chain: string): { symbol: string; contract: string; decimals: number }[] {
  return tokensForChain(chain)
    .filter((t) => !t.isNative && t.contract)
    .map((t) => ({ symbol: t.symbol, contract: t.contract!, decimals: t.decimals }));
}

// Public RPC endpoints — same defaults as routes/wallets.ts RPC_URLS. Swap
// for a paid/private RPC (Alchemy/Infura/etc.) in production for reliability.
export const VAULT_CHAINS: ChainConfig[] = [
  {
    chain: "ETH", rpcUrl: "https://cloudflare-eth.com", chainId: 1,
    nativeSymbol: "ETH", confirmationsRequired: 12, blockRangePerPoll: 20,
    tokens: erc20sFor("ETH"),
  },
  {
    chain: "BSC", rpcUrl: "https://bsc-dataseed.binance.org", chainId: 56,
    nativeSymbol: "BNB", confirmationsRequired: 15, blockRangePerPoll: 40,
    tokens: erc20sFor("BSC"),
  },
  {
    // Chain id/RPC/addresses are unchanged from the "MATIC" days — Polygon's
    // 2024 rebrand only renamed the native-coin ticker to POL, same chain.
    chain: "MATIC", rpcUrl: "https://polygon-rpc.com", chainId: 137,
    nativeSymbol: "POL", confirmationsRequired: 40, blockRangePerPoll: 80,
    tokens: erc20sFor("MATIC"),
  },
  {
    // Plasma Mainnet Beta — EVM L1 for stablecoin payments. USDT on Plasma
    // is "USDT0" (USD₮0), a cross-chain-native Tether variant.
    chain: "PLASMA", rpcUrl: "https://rpc.plasma.to", chainId: 9745,
    nativeSymbol: "XPL", confirmationsRequired: 12, blockRangePerPoll: 60,
    tokens: erc20sFor("PLASMA"),
  },
  {
    // Gas fee on Arbitrum is still ETH — ARB itself is a separate ERC-20
    // (Arbitrum's governance token), watched here alongside USDT.
    chain: "ARB", rpcUrl: "https://arb1.arbitrum.io/rpc", chainId: 42161,
    nativeSymbol: "ETH", confirmationsRequired: 20, blockRangePerPoll: 100,
    tokens: erc20sFor("ARB"),
  },
];

const POLL_INTERVAL_MS = 12_000;
const ERC20_TRANSFER_TOPIC = ethers.id("Transfer(address,address,uint256)");

const providers = new Map<string, ethers.JsonRpcProvider>();
function getProvider(cfg: ChainConfig): ethers.JsonRpcProvider {
  let p = providers.get(cfg.chain);
  if (!p) { p = new ethers.JsonRpcProvider(cfg.rpcUrl, cfg.chainId); providers.set(cfg.chain, p); }
  return p;
}

// Refreshed each poll cycle — every address the vault is willing to receive
// deposits at, lowercased for case-insensitive matching.
let trackedAddresses = new Map<string, { userId: number; walletId: number }>();
async function refreshTrackedAddresses(): Promise<void> {
  const rows = await db.select({
    id: walletsTable.id, userId: walletsTable.userId, address: walletsTable.address,
  }).from(walletsTable);
  const next = new Map<string, { userId: number; walletId: number }>();
  for (const r of rows) next.set(r.address.toLowerCase(), { userId: r.userId, walletId: r.id });
  trackedAddresses = next;
}

async function getCursor(chain: string): Promise<number | null> {
  const { rows } = await pool.query(`SELECT last_block FROM chain_scan_cursor WHERE chain = $1`, [chain]);
  return rows.length ? Number(rows[0].last_block) : null;
}

async function setCursor(chain: string, block: number): Promise<void> {
  await pool.query(
    `INSERT INTO chain_scan_cursor (chain, last_block, updated_at) VALUES ($1, $2, NOW())
     ON CONFLICT (chain) DO UPDATE SET last_block = $2, updated_at = NOW()`,
    [chain, block]
  );
}

async function recordPendingDeposit(row: {
  userId: number; walletId: number; chain: string; tokenSymbol: string;
  tokenContract: string | null; amount: number; fromAddress: string; toAddress: string;
  txHash: string; logIndex: number; blockNumber: number;
}): Promise<boolean> {
  try {
    await db.insert(chainDepositsTable).values({
      userId: row.userId, walletId: row.walletId, chain: row.chain,
      tokenSymbol: row.tokenSymbol, tokenContract: row.tokenContract, amount: row.amount,
      fromAddress: row.fromAddress.toLowerCase(), toAddress: row.toAddress.toLowerCase(),
      txHash: row.txHash, logIndex: row.logIndex, blockNumber: row.blockNumber,
      confirmations: 0, status: "pending", credited: false,
    });
  } catch {
    return false; // unique (chain, tx_hash, log_index) already exists — already seen
  }

  broadcastEvent("deposit_detected", {
    userId: row.userId, walletId: row.walletId, chain: row.chain,
    symbol: row.tokenSymbol, amount: row.amount, txHash: row.txHash,
  });
  await db.execute(dsql`
    INSERT INTO notifications (user_id, type, title, message, data)
    VALUES (${row.userId}, 'deposit', ${`${row.tokenSymbol} deposit detected`},
      ${`${row.amount} ${row.tokenSymbol} incoming on ${row.chain} — waiting for confirmations.`},
      ${JSON.stringify({ chain: row.chain, txHash: row.txHash, amount: row.amount, symbol: row.tokenSymbol })})
  `);
  logBus.system(`Vault deposit detected: ${row.amount} ${row.tokenSymbol} on ${row.chain} (${row.txHash.slice(0, 10)}…) for user ${row.userId}`);
  return true;
}

/** Scan native-coin transfers in [fromBlock, toBlock] against tracked addresses. */
async function scanNativeTransfers(cfg: ChainConfig, provider: ethers.JsonRpcProvider, fromBlock: number, toBlock: number): Promise<void> {
  for (let bn = fromBlock; bn <= toBlock; bn++) {
    const block = await provider.getBlock(bn, true).catch(() => null);
    if (!block) continue;
    for (const txHash of block.transactions) {
      // ethers v6 getBlock(..., true) returns prefetched tx objects when supported,
      // but fall back to a light lookup so this works across RPC quirks.
      const tx = typeof txHash === "string" ? await provider.getTransaction(txHash).catch(() => null) : (txHash as any);
      if (!tx || !tx.to || !tx.value || tx.value === 0n) continue;
      const hit = trackedAddresses.get(String(tx.to).toLowerCase());
      if (!hit) continue;
      await recordPendingDeposit({
        userId: hit.userId, walletId: hit.walletId, chain: cfg.chain,
        tokenSymbol: cfg.nativeSymbol, tokenContract: null,
        amount: parseFloat(ethers.formatEther(tx.value)),
        fromAddress: tx.from ?? "", toAddress: String(tx.to),
        txHash: tx.hash, logIndex: -1, blockNumber: bn,
      });
    }
  }
}

/** Scan ERC-20 Transfer logs for configured token contracts — one eth_getLogs call per token, no full block fetch. */
async function scanTokenTransfers(cfg: ChainConfig, provider: ethers.JsonRpcProvider, fromBlock: number, toBlock: number): Promise<void> {
  if (trackedAddresses.size === 0) return;
  for (const token of cfg.tokens) {
    const logs = await provider.getLogs({
      address: token.contract,
      topics: [ERC20_TRANSFER_TOPIC],
      fromBlock, toBlock,
    }).catch(() => []);
    for (const log of logs) {
      if (log.topics.length < 3) continue;
      const to = ("0x" + log.topics[2].slice(-40)).toLowerCase();
      const hit = trackedAddresses.get(to);
      if (!hit) continue;
      const from = "0x" + log.topics[1].slice(-40);
      const value = BigInt(log.data);
      const amount = parseFloat(ethers.formatUnits(value, token.decimals));
      await recordPendingDeposit({
        userId: hit.userId, walletId: hit.walletId, chain: cfg.chain,
        tokenSymbol: token.symbol, tokenContract: token.contract, amount,
        fromAddress: from, toAddress: to, txHash: log.transactionHash,
        logIndex: log.index, blockNumber: log.blockNumber,
      });
    }
  }
}

/** Bump confirmations on pending deposits for this chain; credit once the threshold is crossed. */
async function confirmPendingDeposits(cfg: ChainConfig, currentBlock: number): Promise<void> {
  const { rows } = await pool.query(
    `SELECT * FROM chain_deposits WHERE chain = $1 AND status = 'pending' ORDER BY id ASC LIMIT 200`,
    [cfg.chain]
  );
  for (const row of rows) {
    const confirmations = Math.max(0, currentBlock - Number(row.block_number) + 1);
    if (confirmations < cfg.confirmationsRequired) {
      await pool.query(`UPDATE chain_deposits SET confirmations = $1 WHERE id = $2`, [confirmations, row.id]);
      continue;
    }

    // Credit: native → that wallet row's on-chain balance display; token → the
    // internal spendable ledger (same table AYZEN's built-in wallet already reads).
    if (!row.token_contract) {
      await db.update(walletsTable)
        .set({ balance: dsql`${walletsTable.balance} + ${row.amount}` as any, updatedAt: new Date() })
        .where(eq(walletsTable.id, row.wallet_id));
    } else {
      await db.execute(dsql`
        INSERT INTO builtin_wallet_tokens (user_id, symbol, amount) VALUES (${row.user_id}, ${row.token_symbol}, ${row.amount})
        ON CONFLICT (user_id, symbol) DO UPDATE SET amount = builtin_wallet_tokens.amount + ${row.amount}, updated_at = NOW()
      `);
    }

    await pool.query(
      `UPDATE chain_deposits SET status = 'confirmed', credited = TRUE, confirmations = $1, confirmed_at = NOW() WHERE id = $2`,
      [confirmations, row.id]
    );
    broadcastEvent("deposit_confirmed", {
      userId: row.user_id, walletId: row.wallet_id, chain: row.chain,
      symbol: row.token_symbol, amount: Number(row.amount), txHash: row.tx_hash,
    });
    broadcastEvent("wallets_updated", { action: "deposit_credited", userId: row.user_id, walletId: row.wallet_id });
    logBus.system(`Vault deposit confirmed & credited: ${row.amount} ${row.token_symbol} on ${row.chain} for user ${row.user_id}`);

    // Wallet↔Finance bridge — best-effort, never blocks the credit above.
    await postDepositToFinance({
      id: row.id, userId: row.user_id, walletId: row.wallet_id, chain: row.chain,
      tokenSymbol: row.token_symbol, tokenContract: row.token_contract, amount: Number(row.amount),
      fromAddress: row.from_address, toAddress: row.to_address, txHash: row.tx_hash,
      logIndex: row.log_index, blockNumber: row.block_number, confirmations,
      status: "confirmed", credited: true, createdAt: row.created_at, confirmedAt: new Date(),
    });
  }
}

async function pollChain(cfg: ChainConfig): Promise<void> {
  const provider = getProvider(cfg);
  const latest = await provider.getBlockNumber();
  let cursor = await getCursor(cfg.chain);
  if (cursor === null) cursor = Math.max(0, latest - 3); // fresh install: start near the tip

  const fromBlock = cursor + 1;
  const toBlock = Math.min(latest, fromBlock + cfg.blockRangePerPoll - 1);

  if (toBlock >= fromBlock) {
    await scanTokenTransfers(cfg, provider, fromBlock, toBlock);
    if (trackedAddresses.size > 0) {
      await scanNativeTransfers(cfg, provider, fromBlock, toBlock);
    }
    await setCursor(cfg.chain, toBlock);
  }

  await confirmPendingDeposits(cfg, latest);
}

let started = false;
export function startDepositWatcher(): void {
  if (started) return;
  started = true;

  // Give startup migrations (chain_deposits / chain_scan_cursor tables) a
  // head start before the first poll touches them.
  setTimeout(async function loop() {
    try {
      await refreshTrackedAddresses();
      await Promise.all(VAULT_CHAINS.map((cfg) =>
        pollChain(cfg).catch((err) => {
          logger.warn({ err, chain: cfg.chain }, "Deposit watcher: chain poll failed");
        })
      ));
    } catch (err: any) {
      logger.warn({ err }, "Deposit watcher: poll cycle failed");
    } finally {
      setTimeout(loop, POLL_INTERVAL_MS);
    }
  }, 15_000);

  logBus.system(`✅ Vault deposit watcher scheduled — watching ${VAULT_CHAINS.map(c => c.chain).join(", ")}`);
}
